apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cong-0306/k8s-manifests.git
    targetRevision: main
    path: hello-app
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-app
  syncPolicy:
    automated:
      prune: true      # 불필요 리소스 자동 정리
      selfHeal: true   # 드리프트 자동 복구
    syncOptions:
      - CreateNamespace=true

